--DISPLAY THE FULL NAME OF CUSTOMER IN A SINGLE FIELD BY MERGING THE FIRSY NAME AND LAST NAMES 
-- AND ADD 10 BONUS POINT TO EACH CUSTIMERS

SELECT 
CUSTOMERID, 
FIRSTNAME,
LASTNAME,
SCORE,
CONCAT(FIRSTNAME, ' ', LASTNAME) FULL_NAME,
COALESCE(SCORE, 0) AS NONNULL_SCORE,
COALESCE(SCORE, 0) + 10 AS NEW_SCORE
FROM SALES.CUSTOMERS

SELECT *
FROM SALES.CUSTOMERS

-- SORT THE SCROES FROM LOWEST TO HIGHESST WITH 
-- WITH BULL APPEARING LAST
SELECT 
SCORE
FROM SALES.CUSTOMERS 
ORDER BY SCORE DESC