--RETREIVE EMPLOYEE DETAILS WITH THEIR GENDERS FULLT EXT DISPLAYED
SELECT
EMPLOYEEID,
FIRSTNAME, 
LASTNAME,
GENDER,
CASE
	WHEN GENDER = 'M' THEN 'MALE'
	WHEN GENDER = 'F' THEN 'FEMALE'
END AS FULLG
FROM SALES.EMPLOYEES

--RETRIEVE CUSOTMERS DETAILS WITH ABBREVIATED COUNTRY NAME 
SELECT *,
CASE COUNTRY 
	WHEN 'GERMANY' THEN 'GE'
	WHEN 'USA'THEN 'US' 
END COUNT_FULLNAME
FROM SALES.CUSTOMERS